<div class="controls">
<?= $this->tabs ?>
</div>

<div class="content">
<h1><?= $this->translate('Configure your first business process') ?></h1>
<p><?= sprintf (
    $this->translate('As no business process has been defined yet you might want to create a %s or upload an %s.'),
    $this->qlink($this->translate('new business process'), 'businessprocess/process/create'),
    $this->qlink($this->translate('existing one'), 'businessprocess/process/upload')
) ?></p>
</div>
