<?php
/** @var \Icinga\Web\View $this */
/** @var \Icinga\Web\Widget\Tabs $tabs */
/** @var string $host */
?>
<div class="controls">
    <?= $tabs->showOnlyCloseButton() ?>
</div>
<div class="content restricted">
    <h1><?= $this->translate('Access Denied') ?></h1>
    <p><?= sprintf($this->translate('You are lacking permission to access host "%s".'), $this->escape($host)) ?></p>
    <a href="#" class="close-container-control action-link"><?= $this->icon('cancel') ?><?= $this->translate('Hide this message') ?></a>
</div>
