<div class="controls">
<?= $this->tabs ?>
  <h1><?= $this->escape($this->title) ?>
  <a href="<?= $this->url()->with('mode', 'toplevel') ?>" title="<?= $this->escape('Switch to toplevel view') ?>"><?= $this->icon('dashboard') ?></a>
  <?= $this->render('simulationlink.phtml') ?>
  <?= $this->render('editlink.phtml') ?>
</h1>
</div>

<div class="content" data-base-target="_next">
  <?= $this->bp->renderHtml($this) ?>
  <?= $this->render('warnings.phtml') ?>
</div>

