<?php if (! $this->compact): ?>
<div class="controls">
<?= $this->tabs ?>
  <h1><?= $this->escape($this->title) ?>
  <a href="<?= $this->url()->with('mode', 'toplevel') ?>" title="<?= $this->escape('Switch to toplevel view') ?>"><?= $this->icon('dashboard') ?></a>
  <?= $this->render('simulationlink.phtml') ?>
  <?= $this->render('editlink.phtml') ?>
</h1>
</div>
<?php endif ?>

<div class="content<?= $this->compact ? ' compact' : '' ?>" data-base-target="_next">
<?php if (! $this->compact): ?>
  <form method="post" action="<?= $this->url()->without('process') ?>" data-base-target="_self">
  <?= $this->formSelect('processName', $this->processName, array('class' => 'autosubmit'), $this->processList) ?>
  </form>
<?php endif ?>
<?php if (! empty($this->errors)): ?>
<ul class="error">
<?php foreach ($this->errors as $error): ?>
<li><?= $this->escape($error) ?></li>
<?php endforeach ?>
</ul>
<?php endif ?>
<?= $this->bp->renderHtml($this) ?>
<?= $this->render('warnings.phtml') ?>
</div>

