name: CI

on:
  push:
    branches:
      - main
      - support/*
  pull_request:
    branches:
      - main

jobs:
  php:
    name: PHP
    uses: Icinga/github-actions/.github/workflows/php.yml@main
    with:
      php-extensions: ldap
      dependencies: |
        {
          "./vendor/icingaweb2-modules/director"  : "https://github.com/Icinga/icingaweb2-module-director.git",
          "./vendor/icingaweb2-modules/icingadb"  : "https://github.com/Icinga/icingadb-web.git"
        }
      env: |
        {
          "ICINGAWEB_CONFIGDIR" : "./test/config"
        }
